# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 08:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reveal_identity', models.BooleanField(default=False)),
                ('body', models.TextField(help_text='say it out!')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
