# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0002_feedback_write_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='make_public',
            field=models.BooleanField(default=False),
        ),
    ]
